options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/i-incentive-465617-g6/python-app/myapp:$SHORT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/i-incentive-465617-g6/python-app/myapp:$SHORT_SHA'
      ]

images:
  - 'us-central1-docker.pkg.dev/i-incentive-465617-g6/python-app/myapp:$SHORT_SHA'
